### PR TITLE
Added API to get videos without tags

### PR DESCRIPTION
**Pull request by sntran**
- New `v3.uploadedVideos` to get videos without tags
- Adjusted coding styles for more readability.

### CODE REVIEW

**Comment by dtex** [comment]
With this patter if we were going to add options to a single method instead of creating a second method I think the params should be wrapped in an object.

````
function uploadedVideos(withTags) {
````

Should be 

````
function uploadedVideos(opts) {
// check opts.withTags instead
````

That way if we decide to add more options/parameters in the future we aren't altering the signature or adding lots of params. That said, I think returning the function might not be the best pattern. It's a clever use of the power of Javascript but any further growth/enhancement could make this pattern really messy. Two separate methods that share/call other private methods would be much easier for average developers to follow and contribute to.

**Comment by sntran** [comment]
Noted. Will make change.

**Comment by sntran** [comment]
@dtex Can you review the changes I have made.

**Comment by dtex** [comment]
I like this structure much better and the commenting is superb.

Do you recall/know what exports.custom is used for?

**Comment by sntran** [comment]
It is the main function (`exports.custom.videosWithKeywords`) that are used in bundles with YouTube. Anadarko is the only one that uses v3.

**Comment by dtex** [comment]
Very cool, thank you!

**Pull request merged**
